apiVersion: v2
name: lakehouse
description: Lakehouse serving layer — ClickHouse query engine and Cube semantic layer
type: application
version: 1.0.6
appVersion: "1.0"
home: https://clickhouse.com
annotations:
  category: analytics
sources:
  - https://github.com/Altinity/clickhouse-operator
  - https://github.com/cube-js/cube
keywords:
  - clickhouse
  - cube
  - analytics
  - s3
  - lakehouse
dependencies: []
