{{- if .Values.clickhouse.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lakehouse.fullname" . }}-backup-script
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
data:
  backup.sh: |-
{{ .Files.Get "scripts/backup.sh" | nindent 4 }}
  prune.sh: |-
{{ .Files.Get "scripts/prune.sh" | nindent 4 }}
{{- end }}
