{{- if and .Values.clickhouse.enabled (not .Values.clickhouse.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakehouse.fullname" . }}-clickhouse
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
stringData:
  password: {{ .Values.clickhouse.password | quote }}
{{- end }}
