{{- if .Values.cube.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakehouse.fullname" . }}-cube
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: cube
type: Opaque
{{- if .Values.cube.jwt.secret }}
stringData:
  jwt-secret: {{ .Values.cube.jwt.secret | quote }}
{{- end }}
{{- end }}
