{{- if .Values.metadata.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakehouse.fullname" . }}-metadata
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: metadata
type: Opaque
stringData:
  password: {{ .Values.metadata.password | default (randAlphaNum 32) | quote }}
{{- end }}
