{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakehouse.fullname" . }}-pgbouncer
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: {{ .Values.postgres.port }}
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "lakehouse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
{{- end }}
