{{- if and (not .Values.s3.existingSecret.name) (or .Values.s3.accessKeyId .Values.s3.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakehouse.fullname" . }}-s3
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
stringData:
  s3AccessKeyId: {{ .Values.s3.accessKeyId | quote }}
  s3SecretAccessKey: {{ .Values.s3.secretAccessKey | quote }}
{{- end }}
