{{- if not .Values.postgres.passwordSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lakehouse.fullname" . }}
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
  {{- if not .Values.s3.existingSecret.name }}
  s3AccessKeyId: {{ .Values.s3.accessKeyId | b64enc | quote }}
  s3SecretAccessKey: {{ .Values.s3.secretAccessKey | b64enc | quote }}
  s3Credentials: {{ printf "{\"name\":\"%s\",\"secret\":\"%s\"}" .Values.s3.accessKeyId .Values.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- if not .Values.nessie.postgres.existingSecret.name }}
  nessie-password: {{ .Values.nessie.postgres.password | b64enc | quote }}
  {{- end }}
{{- end }}
