apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakehouse.fullname" . }}
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    lakehouse/role: primary
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "lakehouse.selectorLabels" . | nindent 4 }}
    lakehouse/role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lakehouse.fullname" . }}-replicas
  labels:
    {{- include "lakehouse.labels" . | nindent 4 }}
    lakehouse/role: replica
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "lakehouse.selectorLabels" . | nindent 4 }}
    lakehouse/role: replica
