apiVersion: v2
name: homepage
description: A highly customizable homepage dashboard
type: application
version: 1.0.1
appVersion: "0.10.9"
home: https://gethomepage.dev
sources:
  - https://github.com/gethomepage/homepage
keywords:
  - homepage
  - dashboard
  - startpage
dependencies:
  - name: common
    version: ">=1.0.0"
    repository: file://../common
