apiVersion: v2
name: dozzle
description: Real-time log viewer for Docker containers
type: application
version: 1.0.0
appVersion: "v10.5.2"
home: https://dozzle.dev
sources:
  - https://github.com/amir20/dozzle
keywords:
  - dozzle
  - logs
  - docker
  - monitoring
dependencies:
  - name: common
    version: 1.0.2
    repository: oci://ghcr.io/vardis-data/charts
