{{- if .Values.postgrest.enabled }}
{{- $password := randAlphaNum 32 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-duckdb.fullname" . }}-postgrest
  labels:
    {{- include "pg-duckdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
type: Opaque
stringData:
  anon-role-password: {{ $password | quote }}
  db-uri: {{ printf "postgres://%s:%s@%s-replicas:%d/%s" .Values.postgrest.anonRole $password (include "pg-duckdb.fullname" .) (.Values.postgres.port | int) .Values.postgres.database | quote }}
  {{- if and .Values.postgrest.jwt.enabled (not .Values.postgrest.jwt.existingSecret.name) }}
  jwt-secret: {{ .Values.postgrest.jwt.secret | default (randAlphaNum 64) | quote }}
  {{- end }}
{{- end }}
