{{- if and .Values.postgrest.enabled .Values.postgrest.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pg-duckdb.fullname" . }}-postgrest
  labels:
    {{- include "pg-duckdb.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
  {{- with .Values.postgrest.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.postgrest.ingress.className }}
  ingressClassName: {{ .Values.postgrest.ingress.className }}
  {{- end }}
  {{- if .Values.postgrest.ingress.tls }}
  tls:
    {{- range .Values.postgrest.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.postgrest.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "pg-duckdb.fullname" $ }}-postgrest
                port:
                  number: {{ $.Values.postgrest.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
