{{- if not .Values.passwordSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-duckdb.secretName" . }}
  labels:
    {{- include "pg-duckdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
  {{- if and .Values.s3.accessKeyId (not .Values.s3.existingSecret.name) }}
  s3AccessKeyId: {{ .Values.s3.accessKeyId | quote }}
  s3SecretAccessKey: {{ .Values.s3.secretAccessKey | quote }}
  {{- end }}
{{- end }}
