apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg-duckdb.fullname" . }}
  labels:
    {{- include "pg-duckdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "pg-duckdb.selectorLabels" . | nindent 4 }}
    pg-duckdb/role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg-duckdb.fullname" . }}-replicas
  labels:
    {{- include "pg-duckdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "pg-duckdb.selectorLabels" . | nindent 4 }}
    pg-duckdb/role: replica
