image:
  repository: sosedoff/pgweb
  # renovate: datasource=docker depName=sosedoff/pgweb
  tag: "0.17.0"
  pullPolicy: IfNotPresent

replicaCount: 1

existingSecret:
  enabled: false
  name: ""
  keys:
    databaseUrl: "databaseUrl"
    authUser: "authUser"
    authPass: "authPass"

database:
  host: ""
  port: 5432
  name: ""
  user: ""
  password: ""
  sslMode: disable

server:
  host: "0.0.0.0"
  port: 8081
  readOnly: false
  sessions: true
  lockSession: false
  prefix: ""

auth:
  enabled: false
  user: ""
  pass: ""

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false
  className: tailscale
  hostname: pgweb
  tags: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

reloader:
  enabled: true
