{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Values.certManager.secretNamespace }}
  labels:
    {{- include "cloudflare-ingress.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.certManager.apiToken | quote }}
{{- end }}
