{{- if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-ingress.cloudflaredName" . }}-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-ingress.labels" . | nindent 4 }}
type: Opaque
stringData:
  TUNNEL_TOKEN: {{ .Values.cloudflared.tunnelToken | quote }}
{{- end }}
