{{- if .Values.cloudflared.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-ingress.fullname" . }}-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-ingress.labels" . | nindent 4 }}
type: Opaque
stringData:
  TUNNEL_TOKEN: ref+envsubst://$CLOUDFLARE_TUNNEL_TOKEN
{{- end }}
