apiVersion: v2
name: system-upgrade-controller
description: Kubernetes-native upgrade controller for nodes using declarative Plans
type: application
version: 0.1.1
appVersion: v0.19.0
home: https://github.com/rancher/system-upgrade-controller
sources:
  - https://github.com/rancher/system-upgrade-controller
keywords:
  - kubernetes
  - upgrades
  - k3s
  - system-upgrade
