apiVersion: v2
name: nginx-s3-gateway
description: Official nginx S3 gateway with caching
type: application
version: 1.0.1
appVersion: "latest"
dependencies:
  - name: common
    version: "1.0.1"
    repository: "https://vardis-data.github.io/charts"
