apiVersion: v2
name: pipelines
description: Generate Kubernetes manifests for vardis data pipelines
type: application
version: 1.1.1
appVersion: 1.0.0
home: https://github.com/vardis-data/pipelines
sources:
  - https://github.com/vardis-data/pipelines
keywords:
  - pipeline
  - argo-workflows
  - data-engineering
