pipeline:
  name: ""
  datasetName: ""
  schedule: "0 0 * * 1"
  env: {}

  nodeSelector:
    workload-type: jobs

  tolerations:
    - key: workload-type
      operator: Equal
      value: jobs
      effect: NoSchedule

  image:
    repository: ghcr.io/vardis-data/pipelines
    name: ""
    tag: ""
    pullPolicy: Always

  resources:
    parallelism: 2
    retryLimit: 3

  logging:
    level: INFO

  storage:
    overwriteParquetFiles: false

namespace: pipelines

imagePullSecrets:
  - name: ghcr-secret

sharedConfigMap: pipelines-variables
sharedSecret: pipelines-secrets

imageUpdater:
  enabled: false
  applicationRef: ""
  imageName: workflow-submitter
  image: ""
  updateStrategy: latest
  allowTags:
    - regexp: ^main-.*$
  pullPolicy: Always
  writeBack:
    method: git
    gitBranch: main
