apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "system-upgrade-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
data:
  SYSTEM_UPGRADE_CONTROLLER_DEBUG: {{ .Values.controller.debug | quote }}
  SYSTEM_UPGRADE_CONTROLLER_THREADS: {{ .Values.controller.threads | quote }}
  SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: {{ .Values.job.activeDeadlineSeconds | quote }}
  SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: {{ .Values.job.backoffLimit | quote }}
  SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: {{ .Values.kubectlImage.pullPolicy | quote }}
  SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: {{ include "system-upgrade-controller.kubectlImage" . | quote }}
  SYSTEM_UPGRADE_JOB_PRIVILEGED: {{ .Values.job.privileged | quote }}
  SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: {{ .Values.job.ttlSecondsAfterFinish | quote }}
  SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: {{ .Values.plan.pollingInterval | quote }}
