image:
  repository: ghcr.io/kanbn/kan
  # renovate: datasource=docker depName=ghcr.io/kanbn/kan
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

baseUrl: ""
betterAuthSecret: ""

database:
  host: ""
  port: 5432
  name: kan
  user: kan
  password: ""

s3:
  enabled: false
  endpoint: ""
  region: ""
  avatarBucket: ""
  accessKeyId: ""
  secretAccessKey: ""
  forcePathStyle: true
  existingSecret:
    name: ""
    keys:
      accessKeyId: "s3AccessKeyId"
      secretAccessKey: "s3SecretAccessKey"

smtp:
  enabled: false
  host: ""
  port: 587
  username: ""
  password: ""
  secure: true
  fromAddress: ""
  existingSecret:
    name: ""
    keys:
      password: "smtpPassword"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: tailscale
  hostname: kan
  tags: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

reloader:
  enabled: true

postgres:
  enabled: true
  customUser:
    name: kan
    database: kan
    password: ""
  persistence:
    enabled: true
    size: 1Gi
