apiVersion: v2
name: cloudflare-gateway
description: Cloudflare Tunnel + Gateway API gateway for vardis.space
type: application
version: 1.0.1
appVersion: "1.0.0"
home: https://github.com/vardis-data/charts
sources:
  - https://github.com/vardis-data/charts
keywords:
  - cloudflare
  - tunnel
  - gateway-api
  - traefik
  - ingress
