apiVersion: v2
name: docmost
description: Open-source collaborative documentation and wiki software
type: application
version: 1.4.0
appVersion: 0.8.2
home: https://docmost.com
sources:
  - https://github.com/docmost/docmost
keywords:
  - documentation
  - wiki
  - collaboration
dependencies:
  - name: common
    version: 1.0.1
    repository: oci://ghcr.io/vardis-data/charts
  - name: postgres
    version: 0.18.3
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
  - name: valkey
    version: 0.9.3
    repository: https://valkey.io/valkey-helm
    condition: valkey.enabled
