apiVersion: v2
name: docmost
description: Open-source collaborative documentation and wiki software
type: application
version: 0.1.0
appVersion: 0.8.2
home: https://docmost.com
sources:
  - https://github.com/docmost/docmost
keywords:
  - documentation
  - wiki
  - collaboration
