image:
  repository: docmost/docmost
  # renovate: datasource=docker depName=docmost/docmost
  tag: "0.8.2"
  pullPolicy: IfNotPresent

replicaCount: 1

appUrl: ""
appSecret: ""

existingSecret:
  enabled: false
  name: ""
  keys:
    appSecret: "appSecret"
    databasePassword: "databasePassword"
    redisPassword: "redisPassword"
    s3AccessKeyId: "s3AccessKeyId"
    s3SecretAccessKey: "s3SecretAccessKey"
    smtpPassword: "smtpPassword"

database:
  host: ""
  port: 5432
  name: docmost
  user: docmost
  password: ""

redis:
  host: ""
  port: 6379
  password: ""

valkey:
  enabled: true
  password: ""
  replicaCount: 1
  dataStorage:
    enabled: false
  service:
    type: ClusterIP
    port: 6379
  metrics:
    enabled: true
  auth:
    enabled: true
    usersExistingSecret: "docmost-valkey-auth"
    aclUsers:
      default:
        permissions: "~* &* +@all"

s3:
  enabled: false
  endpoint: ""
  region: ""
  bucket: ""
  accessKeyId: ""
  secretAccessKey: ""
  forcePathStyle: true

smtp:
  enabled: false
  host: ""
  port: 587
  username: ""
  password: ""
  secure: true
  fromAddress: ""
  fromName: "Docmost"

service:
  type: ClusterIP
  port: 80

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5

resources: {}

reloader:
  enabled: true

postgres:
  enabled: true
  customUser:
    name: docmost
    database: docmost
    password: ""
  persistence:
    enabled: true
    size: 5Gi
