apiVersion: v2
name: cloudflare-ingress
description: Cloudflare Tunnel + cert-manager ClusterIssuer + wildcard Certificate for vardis.space
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/vardis-data/charts
sources:
  - https://github.com/vardis-data/charts
keywords:
  - cloudflare
  - tunnel
  - cert-manager
  - traefik
  - ingress
