{{- if .Values.litestream.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kan.fullname" . }}-litestream
  labels:
    {{- include "kan.labels" . | nindent 4 }}
data:
  litestream.yml: |
    dbs:
      - path: {{ .Values.sqlite.path }}
        replicas:
          - url: s3://{{ .Values.litestream.s3.bucket }}/{{ .Values.litestream.s3.path }}
            endpoint: {{ .Values.litestream.s3.endpoint }}
{{- end }}
