apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipeline.configmapName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
data:
  {{- $env := .Values.pipeline.env | default dict }}
  {{- if not (hasKey $env "K8S_IMAGE_PULL_POLICY") }}
  K8S_IMAGE_PULL_POLICY: {{ .Values.pipeline.image.pullPolicy | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_BATCH_SIZE") }}
  PIPELINE_BATCH_SIZE: {{ .Values.pipeline.resources.batchSize | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_DEFAULT_IMAGE") }}
  PIPELINE_DEFAULT_IMAGE: {{ include "pipeline.fullImageName" . | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_NAME") }}
  PIPELINE_NAME: {{ include "pipeline.name" . | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_OVERWRITE_PARQUET_FILES") }}
  PIPELINE_OVERWRITE_PARQUET_FILES: {{ include "pipeline.overwriteParquetFiles" . | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_PARALLELISM") }}
  PIPELINE_PARALLELISM: {{ .Values.pipeline.resources.parallelism | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_RETRY_LIMIT") }}
  PIPELINE_RETRY_LIMIT: {{ .Values.pipeline.resources.retryLimit | quote }}
  {{- end }}
  {{- if not (hasKey $env "PIPELINE_SCHEDULE_CRON") }}
  PIPELINE_SCHEDULE_CRON: {{ .Values.pipeline.schedule | quote }}
  {{- end }}
  {{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
