apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pipeline.configmapName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
data:
  PIPELINE_NAME: {{ include "pipeline.name" . | quote }}
  PIPELINE_DATASET_NAME: {{ include "pipeline.datasetName" . | quote }}
  PIPELINE_OVERWRITE_PARQUET_FILES: {{ .Values.pipeline.storage.overwriteParquetFiles | quote }}
  LOG_LEVEL: {{ .Values.pipeline.logging.level | quote }}
  {{- range $key, $value := .Values.pipeline.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
