{{- if .Values.imageUpdater.enabled }}
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ include "pipeline.releaseName" . }}
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
spec:
  namespace: {{ .Values.imageUpdater.argocdNamespace }}
  applicationRefs:
    - namePattern: {{ .Values.imageUpdater.applicationRef | default (include "pipeline.releaseName" .) }}
      images:
        - alias: {{ include "pipeline.releaseName" . }}
          imageName: {{ .Values.imageUpdater.image | default (include "pipeline.fullImageName" .) }}
          commonUpdateSettings:
            updateStrategy: {{ .Values.imageUpdater.updateStrategy }}
            {{- with .Values.imageUpdater.allowTags }}
            allowTags: {{ . | quote }}
            {{- end }}
  {{- with .Values.imageUpdater.writeBack }}
  writeBackConfig:
    method: {{ .method }}
    {{- with .gitBranch }}
    gitConfig:
      branch: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
