apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pipeline.jobName" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "pipeline.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: workflow-submitter
          image: {{ include "pipeline.fullImageName" . }}
          command:
            - "uv"
            - "run"
            - "--no-dev"
            - "--package"
            - {{ include "pipeline.packageName" . | quote }}
            - "python"
            - "-m"
            - {{ printf "%s.main" (include "pipeline.packageName" .) | quote }}
          env:
            - name: PIPELINE_DATASET_NAME
              value: {{ include "pipeline.datasetName" . | quote }}
            - name: PIPELINE_NAME
              value: {{ include "pipeline.name" . | quote }}
            - name: PIPELINE_SCHEDULE_CRON
              value: {{ .Values.pipeline.schedule | quote }}
            - name: PIPELINE_DEFAULT_IMAGE
              value: {{ include "pipeline.fullImageName" . | quote }}
            - name: K8S_IMAGE_PULL_POLICY
              value: {{ .Values.pipeline.image.pullPolicy | quote }}
            - name: PIPELINE_PARALLELISM
              value: {{ .Values.pipeline.resources.parallelism | quote }}
            - name: PIPELINE_BATCH_SIZE
              value: {{ .Values.pipeline.resources.batchSize | quote }}
            - name: PIPELINE_MULTIPROCESSING_WORKERS
              value: {{ .Values.pipeline.resources.multiprocessingWorkers | quote }}
            - name: PIPELINE_RETRY_LIMIT
              value: {{ .Values.pipeline.resources.retryLimit | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.pipeline.logging.level | quote }}
            - name: PIPELINE_OVERWRITE_PARQUET_FILES
              value: {{ .Values.pipeline.storage.overwriteParquetFiles | quote }}
            {{- range $key, $value := .Values.pipeline.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.sharedConfigMap }}
            - secretRef:
                name: {{ .Values.sharedSecret }}
