{{- if not .Values.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbackweb.fullname" . }}
  labels:
    {{- include "pgbackweb.labels" . | nindent 4 }}
type: Opaque
stringData:
  PBW_ENCRYPTION_KEY: {{ .Values.encryptionKey | quote }}
  PBW_POSTGRES_CONN_STRING: {{ include "pgbackweb.databaseUrl" . | quote }}
{{- end }}
