{{- if .Values.ingress.enabled }}
{{- if eq .Values.ingress.className "tailscale" }}
{{- $tailscaleValues := merge . (dict "Values" (merge .Values (dict "tailscale" (dict "enabled" true "hostname" .Values.ingress.hostname "tags" .Values.ingress.tags)))) }}
{{- include "vardis-common.tailscale-ingress" $tailscaleValues }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-s3-gateway.fullname" . }}
  labels:
    {{- include "nginx-s3-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  defaultBackend:
    service:
      name: {{ include "nginx-s3-gateway.fullname" . }}
      port:
        number: {{ .Values.service.port }}
{{- end }}
{{- end }}
