{{- if .Values.ingress.enabled }}
{{- if eq .Values.ingress.className "tailscale" }}
{{- $tailscaleValues := merge . (dict "Values" (merge .Values (dict "tailscale" (dict "enabled" true "hostname" .Values.ingress.hostname "tags" .Values.ingress.tags)))) }}
{{- include "common.tailscale-ingress" $tailscaleValues }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-s3-gateway.fullname" . }}
  labels:
    {{- include "nginx-s3-gateway.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.hosts }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "nginx-s3-gateway.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- else }}
  defaultBackend:
    service:
      name: {{ include "nginx-s3-gateway.fullname" . }}
      port:
        number: {{ .Values.service.port }}
  {{- end }}
{{- end }}
{{- end }}
