{{- if .Values.s3.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-s3-gateway.fullname" . }}
  labels:
    {{- include "nginx-s3-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.s3.accessKey | b64enc | quote }}
  secret-key: {{ .Values.s3.secretKey | b64enc | quote }}
{{- end }}
