{{- if and .Values.valkey.enabled .Values.valkey.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "docmost.fullname" . }}-valkey-auth
  labels:
    {{- include "docmost.labels" . | nindent 4 }}
type: Opaque
stringData:
  default: {{ .Values.valkey.password | quote }}
{{- end }}
