{{- if .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: ref+envsubst://$CLOUDFLARE_API_TOKEN
{{- end }}
