{{- if .Values.cloudflared.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflare-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflare-gateway.labels" . | nindent 4 }}
spec:
  {{- if .Values.cloudflared.replicas }}
  replicas: {{ .Values.cloudflared.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudflare-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudflare-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.cloudflared.image.repository }}:{{ .Values.cloudflared.image.tag }}"
          imagePullPolicy: {{ .Values.cloudflared.image.pullPolicy }}
          args:
            {{- toYaml .Values.cloudflared.args | nindent 12 }}
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "cloudflare-gateway.fullname" . }}-tunnel
                  key: TUNNEL_TOKEN
          {{- with .Values.cloudflared.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.cloudflared.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
