{{- if not .Values.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgweb.fullname" . }}
  labels:
    {{- include "pgweb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.database.host .Values.database.name }}
  DATABASE_URL: {{ include "pgweb.databaseUrl" . | quote }}
  {{- end }}
  {{- if .Values.auth.enabled }}
  AUTH_USER: {{ .Values.auth.user | quote }}
  AUTH_PASS: {{ .Values.auth.pass | quote }}
  {{- end }}
{{- end }}
