name: Release Charts

on:
  push:
    branches: [main]
    paths: [charts/**]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { fetch-depth: 0 }
      - uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Add external repos
        run: helm repo add valkey https://valkey.io/valkey-helm

      - uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Lint
        run: ct lint --config ct.yaml --all

      - uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          skip_existing: true
          skip_upload: true

      - uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        env:
          REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts
        run: |
          for tgz in .cr-release-packages/*.tgz; do
            helm push "$tgz" "$REGISTRY"
          done
