image:
  repository: eduardolat/pgbackweb
  # renovate: datasource=docker depName=eduardolat/pgbackweb
  tag: "0.5.1"
  pullPolicy: IfNotPresent

replicaCount: 1

encryptionKey: ""

existingSecret:
  enabled: false
  name: ""
  keys:
    encryptionKey: "encryptionKey"
    databaseUrl: "databaseUrl"

database:
  host: ""
  port: 5432
  name: pgbackweb
  user: pgbackweb
  password: ""
  sslMode: disable

server:
  host: "0.0.0.0"
  port: 8085
  pathPrefix: ""

timezone: "UTC"

localStorage:
  enabled: false
  size: 10Gi
  storageClassName: ""

service:
  type: ClusterIP
  port: 8085

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

reloader:
  enabled: true

postgres:
  enabled: true
  customUser:
    name: pgbackweb
    database: pgbackweb
    password: ""
  persistence:
    enabled: true
    size: 1Gi
